# Generated by Django 3.2.7 on 2022-01-23 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='items',
            new_name='cartitems',
        ),
    ]
